### ISSUE TITLE
Delete sessions from database

### ISSUE THREAD

**Issue by maddy2get** [mweibel/connect-session-sequelize#1]
Hi there,

I am using this module for my session store. Just wondering if there is any way that session can get deleted automatically from database after some time?

Thanks for your time.

Cheers,
Sanjay

**Comment by dantman** [comment]
No, the maxAge property is a cookie setting.

connect-session doesn't do any purging of old sessions.

**Comment by dantman** [comment]
I've implemented session expiration in [a branch](https://github.com/dantman/connect-session-sequelize/compare/dantman:master...expiration?expand=1)

I'll make a pull request for it once my other one is merged.
