### ISSUE TITLE
TypeError: sessionStore.destroy is not a function

### ISSUE THREAD

**Issue by pacmac** [mweibel/connect-session-sequelize#101]
I have just setup using sqlite, and found an issue related to this error:

`TypeError: sessionStore.destroy is not a function`

However after applying this fix, I still get the same error:

```
  var sequelize = new Sequelize(
    "database",
    "username",
    "password", {
      "dialect"   : "sqlite",
      "storage"   : ":memory:"
    },
    {
      query:{
        raw:false
      }
    }
  );
```

How can I solve it ?

**Comment by mweibel** [comment]
how would I know? please add more info. Impossible to help you with this amount of information.
Best is a reproduction case in a public github repo.

**Comment by pacmac** [comment]
OK, sessionStore.destroy() appears to be a method used in the default express sessionStore.

I have worked around it

Thanks anyway.
