### ISSUE TITLE
Change default generated session table and Queries back to "Sessions"

### ISSUE THREAD

**Issue by Jolare** [mweibel/connect-session-sequelize#102]
With one of the latest changes to this fantastic middleware, queries now default for the table "Session" with no table or tableName options defined. It used to query for the table "Sessions" and the generated table in the database is "Sessions" that was generated with a previous version. This breaks and crashes my application. I have renamed the table in the database to "Session" to fix this for now for ease of use.

I think the problem is that the default table name value is now modelKey which is "Session", but used to be "Sessions" as can still be seen in the current code in defaultOptions.tableName.

**Comment by mweibel** [comment]
I think that should be resolved with https://github.com/mweibel/connect-session-sequelize/issues/97, no?

**Comment by Jolare** [comment]
I am on 6.1.1 and it is still looking for "Session" by default when no options except db are defined for the store. I mean either way, it is probably also not a good idea to change it back at this point because it would potentially break all the new installations since 6.1.0
With the next update to my application I am gonna define the table with a name in the store and change the database table name back, that is probably the easiest way and should prevent breaking in the future.

**Comment by mweibel** [comment]
hmm. weird. 
Yeah I guess that's the best option. Sorry about that!
