### ISSUE TITLE
Sequelize v6 beta: bluebird removed so .spread does not work

### ISSUE THREAD

**Issue by seeARMS** [mweibel/connect-session-sequelize#105]
I'm trying to log in a user using Sequelize v6. 

It looks like `this.sessionModel.findCreateFind(...)` returns a native ES6 `Promise { <pending> }` in Sequelize v6, and thus `.spread` does not work directly (since it looks like `.spread` only works on BlueBird promises). 

The upgrade docs confirm Bluebird promises were removed in v6: https://sequelize.org/master/manual/upgrade-to-v6.html

**Comment by mweibel** [comment]
Feel free to send a PR 👍

**Comment by pruhstal** [comment]
@mweibel Sequelize v6 has now been released. What's the goal here -- do you intend to re-write this in TypeScript or do you want to throw a band-aid on for now with Bluebird? I can whip up a quick PR, if the latter.

**Comment by mweibel** [comment]
Why a rewrite in TypeScript?
Node/JS has Promises support as well, also without bluebird.

**Comment by mweibel** [comment]
@seeARMS @pruhstal connect-session-sequelize 7.0.0 has been released.
