### ISSUE TITLE
Sequelize v6.1.0 - this.sessionModel.findOne(...).then(...).asCallback is not a function Error

### ISSUE THREAD

**Issue by raugaral** [mweibel/connect-session-sequelize#108]
Yesterday the new Sequelize version came out, they have changed little but apparently connect-session doesn't work...

> TypeError: this.sessionModel.findOne(...).then(...).asCallback is not a function
>     at SequelizeStore.get (/Users/raul/Documents/git_projects/web/Bayazi/node/node_modules/connect-session-sequelize/lib/connect-session-sequelize.js:73:10)
>     at session (/Users/raul/Documents/git_projects/web/Bayazi/node/node_modules/express-session/index.js:481:11)
>     at Layer.handle [as handle_request] (/Users/raul/Documents/git_projects/web/Bayazi/node/node_modules/express/lib/router/layer.js:95:5)
>     at trim_prefix (/Users/raul/Documents/git_projects/web/Bayazi/node/node_modules/express/lib/router/index.js:317:13)
>     at /Users/raul/Documents/git_projects/web/Bayazi/node/node_modules/express/lib/router/index.js:284:7
>     at Function.process_params (/Users/raul/Documents/git_projects/web/Bayazi/node/node_modules/express/lib/router/index.js:335:12)
>     at next (/Users/raul/Documents/git_projects/web/Bayazi/node/node_modules/express/lib/router/index.js:275:10)
>     at internalNext (/Users/raul/Documents/git_projects/web/Bayazi/node/node_modules/helmet/dist/index.js:65:24)
>     at xXssProtection (/Users/raul/Documents/git_projects/web/Bayazi/node/node_modules/x-xss-protection/dist/index.js:47:13)
>     at internalNext (/Users/raul/Documents/git_projects/web/Bayazi/node/node_modules/helmet/dist/index.js:68:13)

**Comment by mweibel** [comment]
Duplicate. See #105 #106 #107

**Comment by mweibel** [comment]
@raugaral connect-session-sequelize 7.0.0 has been released
