### ISSUE TITLE
"UnhandledPromiseRejectionWarning: SequelizeConnectionRefusedError: connect ECONNREFUSED" error unhandled correctly

### ISSUE THREAD

**Issue by TitaneBoy** [mweibel/connect-session-sequelize#110]
Hi there..

I'm facing an little issue with your module. It seems that connect-session-sequelize does not handle properly a promise when trying to delete a session on a database that was disconnected in the time.

![image](https://user-images.githubusercontent.com/15614466/88388529-af607c00-cd82-11ea-9a3b-5cbb8ba69a76.png)

After investiguation, it seems that the proplem is located at the clearExpiredSessions function, when calling the "destroy" function of the session model

![image](https://user-images.githubusercontent.com/15614466/88389330-50036b80-cd84-11ea-890e-bc12541595fd.png)

The rejection is done in the "connect" function of sequelize

![image](https://user-images.githubusercontent.com/15614466/88389526-a96b9a80-cd84-11ea-81c6-0321fa0b47ff.png)

In my humble opinion, a quick fix for this issue would be to add a "catch" at the end of the "destroy" call, like this:

![image](https://user-images.githubusercontent.com/15614466/88389687-f0f22680-cd84-11ea-9d23-37dce4eb8e7f.png)

I've tested this fix on my side and there is no more unhandled promise rejection anymore from connect-session-sequelize

Would be great to have this little fix soon on npm.

Thanks for your help & answer.

**Comment by TitaneBoy** [comment]
PS: I'm using connect-session-sequelize with the "expres-session" module

```
import session from 'express-session';
const sequelizeStoreOptions = {
    checkExpirationInterval: 30000,
    db: sequelizer,
    table: 'Sessions',
  }

  if (sessionTimeOut !== 0) {
    sequelizeStoreOptions.expiration = (sessionTimeOut * 60 * 1000);
  }

  const myStore = new sequelizeStore(sequelizeStoreOptions);
  const app = express();

  myStore.sync()
    .catch(() => {
      //Do nothing
    });

  app.use(session({
    cookie: {
      httpOnly: true,
      secure: useSecureSessions(),
    },
    genid: () => genuuid(),
    resave: false,
    saveUninitialized: false,
    secret: 'blablablafornow',
    store: myStore,
  }));
```

**Comment by mweibel** [comment]
Sounds good. Feel free to submit a PR. The debug message could be improved by specifying what was done which triggered that error (e.g. `Ignoring error at clearExpiredSessions: ${error}`).

**Comment by TitaneBoy** [comment]
Thanks for your quick answer...Will try to do it soon

**Comment by TitaneBoy** [comment]
The [PR](https://github.com/mweibel/connect-session-sequelize/pull/111)  is submitted. Thank you :-)

**Comment by mweibel** [comment]
closing as #111 has been merged and will be released soon.

**Comment by mweibel** [comment]
version 7.0.1 released on npm.

**Comment by TitaneBoy** [comment]
Thank you very much for your quick actions & answers...  :-)
