### ISSUE TITLE
Duplicate database queries?

### ISSUE THREAD

**Issue by bhairava3** [mweibel/connect-session-sequelize#114]
Hi, I just started learning node.

server.js
![server.js](https://raw.githubusercontent.com/bhairava3/etc/master/server.jpg)

middleware.js
![middleware.js](https://raw.githubusercontent.com/bhairava3/etc/master/middleware.jpg)

After requesting the server only 1 time, 4 database queries appear on the command line, instead of the expected two, is that correct?

cmd:
![cmd](https://raw.githubusercontent.com/bhairava3/etc/master/cmd.jpg)

**Comment by mweibel** [comment]
if you run the server with the env variable `DEBUG` set to `*` you'll see more info on what happens. 
Usually browsers request more than just the index, maybe e.g. the favicon is also routed through node and therefore triggers a session select/update.

It's cool that you learned to code and that you inspect everything you do, however you might be focusing on the wrong thing if you start to suspect performance issues in libraries ;)

**Comment by bhairava3** [comment]
TNX :+1:
