### ISSUE TITLE
Version 7.0.2 did not publish TypeScript definition file

### ISSUE THREAD

**Issue by AlanMorel** [mweibel/connect-session-sequelize#117]
Sorry to bother but it looks like after you published 7.0.2, the `index.d.ts` file did not reach npm, and thus updating does not provide users with that file. I'm fairly new to how npm publishing works but I think the issue is that you have a `files` array inside your `package.json` which tells npm what to actually publish, and it excludes everything else. I believe all you need to do is add `index.d.ts` to that `files` array, maybe bump the version one more time, and it should publish it.

Examples `files` array from another project's `package.json`: https://github.com/3lvcz/immutability-helper-functions/blob/08f5f58b9e4f264d0a9f4316a7f56ae3b99d40ed/package.json

StackOverflow where I got this info from: https://stackoverflow.com/questions/27049192/npm-publish-isnt-including-all-my-files

I would have just opened this PR for you but I had no way of validating locally whether this fixes the issue or not, so I figured I'd just open an issue instead and allow you confirm the fix.

Thanks again!

**Comment by mweibel** [comment]
thanks - fixed now. 👍
