### ISSUE TITLE
Custom fields never get saved to the database

### ISSUE THREAD

**Issue by uehlbran** [mweibel/connect-session-sequelize#136]
To re-create the issue simply follow the directions in the readme. You'll notice that custom fields never get populated in the database. They will appear on the actual session object and there will be a spot in the database for them but, the SQL that is generated completely ignores them.

"Executing (default): INSERT INTO `Sessions` (`sid`,`expires`,`data`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?);"

```
sequelize.define("Session", {
    sid: {
        type: DataTypes.STRING,
        primaryKey: true,
    },
    userId: DataTypes.STRING,
    expires: DataTypes.DATE,
    data: DataTypes.TEXT,
});

function extendDefaultFields(defaults, session) {
    console.log(defaults, session)
    return {
        data: defaults.data,
        expires: defaults.expires,
        userId: session.userId,
    };
}

session({
    secret: 'secret',
    store: new SequelizeStore({
        db: sequelize,
        extendDefaultFields: extendDefaultFields
    }),
    resave: true,
    saveUninitialized: false,
    cookie: {
        httpOnly: true
    },
});

const sequelize = new Sequelize(
    'node',
    'username',
    'password,
    {
        dialect: 'mysql',
        host: 'localhost'
    }
);
```

Here's the DDL for the Session table:

```
-- auto-generated definition
create table sessions
(
    sid       varchar(255) not null
        primary key,
    userId    varchar(255) null,
    expires   datetime     null,
    data      text         null,
    createdAt datetime     not null,
    updatedAt datetime     not null
);
```

**Comment by mweibel** [comment]
hi,

there's an example repo ([documented in the README](https://github.com/mweibel/connect-session-sequelize#contributingreporting-bugs)) which should be used to submit issues: https://github.com/mweibel/connect-session-sequelize-example

Please next time add a clear reproduction case with an example repository forked from my repository. 

I added the steps required to use `extendDefaultFields` in a branch: https://github.com/mweibel/connect-session-sequelize-example/tree/extend-default-fields
It works for me.

Reopen the issue once you have a running example where it does not work.
