### ISSUE TITLE
Destroying a session throws a TypeError

### ISSUE THREAD

**Issue by suksant** [mweibel/connect-session-sequelize#16]
Whenever I try to logout by doing req.session.destroy() it throws:

Possibly unhandled TypeError: undefined is not a function
    at errorDestroying (~/node_modules/connect-session-sequelize/lib/connect-session-sequelize.js:110:6)

The session was actually destroyed properly but the fn() is undefined; hence, throwing an error. Currently, I just check if fn is undefined in the destroySession(sid, fn) method. But did I miss anything else?

**Comment by mweibel** [comment]
Should be fixed with the latest version
