### ISSUE TITLE
Local Environment Problems

### ISSUE THREAD

**Issue by busheezy** [mweibel/connect-session-sequelize#23]
This gives me problems on a local machine.  I've tried from multiple machines and if I'm browsing from the same machine the server is running then my website quits working as intended.

**Comment by mweibel** [comment]
Could you explain what you mean? What's not working? How's your setup? Example code?

**Comment by busheezy** [comment]
I'm sorry.  I was thinking about how terribly vague I was.  My bug appeared when I was separating my passport code into a common js module.  I just moved my code to my main app file and it works fine.  

It was not allowing me to login/logout properly and I'm not sure what was going on.

Thanks for your work.

**Comment by busheezy** [comment]
I'm sorry to bother.  I thought I had it fixed.  It turns out I just had it formatted so sessions weren't even being made.  I still have the problem on my local client.

When I'm on connecting from my local address the site no longer lets me login/logout correctly.

**Comment by busheezy** [comment]
The login/logout behavior is no longer consistent when I enable this plugin on a local environment.  I can login/logout several times before I can make the action work.  If I spam the button before a page load sometimes I can get it to go through.  I can make a test environment for you if you want.

**Comment by jakeorr** [comment]
It's hard to know what you're trying to do without some example code, but you might be running into an issue similar to [this](https://github.com/mweibel/connect-session-sequelize/issues/20#issuecomment-135557423). Try wrapping your redirect after signin/out in a `req.session.save` as described in that linked comment.

**Comment by busheezy** [comment]
Thank you very much @jakeorr.  I made my code look as follows and it started to work.

```
  app.get('/login', function(req, res){
    req.session.save(function () {
      res.render('login');
    });
  });

  app.post('/login', passport.authenticate('local-login', { failureRedirect: '/login' }), function(req, res) {
    req.session.save(function () {
      res.redirect('/profile');
    });
  });

  app.get('/register', function(req, res){
    req.session.save(function () {
      res.render('register');
    });
  });

  app.post('/register', passport.authenticate('local-register', { failureRedirect: '/register' }), function(req, res) {
    req.session.save(function () {
      res.redirect('/profile');
    });
  });

  app.get('/logout', function(req, res){
    req.logout();
    req.session.save(function () {
      res.redirect('/');
    });
  });
```

I had no idea how to explain the symptoms but it just felt like something was getting called back too quickly.  Thank you tons.

**Comment by jakeorr** [comment]
No problem, I'm glad that solved it for you! I recognized it because I was dealing with the same issue recently. Cheers.

**Comment by carlitux** [comment]
This shouldn't be fixed so work as any other session store? we won't be able to use the flash passport feature.

**Comment by mweibel** [comment]
Don't know what you mean. Could you setup an example repo or so and tell us what's wrong/ not working?

**Comment by jakeorr** [comment]
@carlitux The issue with flash messages being shown inconsistently was never with this repo. It has to do with [the way the underlying express-session module works](https://github.com/mweibel/connect-session-sequelize/issues/7#issuecomment-59469816). You can use flash messages consistently if you explicitly save the session before ending the response as mentioned above.

**Comment by carlitux** [comment]
@jakeorr  @mweibel I got it... one I had a delay on reload now working. Thank  you very much.
