### ISSUE TITLE
Suggestion: document the required the session Sequelize model

### ISSUE THREAD

**Issue by Askelkana** [mweibel/connect-session-sequelize#27]
Without specifying the sequelize model explicitly using sequelize.define, the sessions were not being saved. I had to trawl through your code to find out the required column names, etc.

Only then was I able to use the .sync method (note: on the sequelize model directly, not the store, which was missing, contrary to what your documentation states).

It may be helpful to specify the required/created session table in the documentation.

**Comment by mweibel** [comment]
Feel free to open a PR with proposed changes :)

**Comment by MtDalPizzol** [comment]
Well, I'm trying to implement this module but I can't run Sequelize.sync();
Could someone tell me what are the required columns for the table so I can create it and define the model without having to run sync()?

**Comment by MtDalPizzol** [comment]
Nevermind. Found it. If someone out there  is looking for it, here it is:

```javascript
module.exports = function(sequelize, DataTypes) {
  return sequelize.define('Session', {
    sid: {
      type: DataTypes.STRING,
      primaryKey: true
    }
    , expires: {
      type: DataTypes.DATE,
      allowNull: true
    }
    , data: DataTypes.TEXT
  });
};
```

**Comment by mweibel** [comment]
@MtDalPizzol why can't you run sync?

@Askelkana revisiting this.. Is a PR coming with the proposed changes or not? Also I wonder why it didn't work for you. If you don't specify a `table` in the options it should create the table based on the model for you.

**Comment by Askelkana** [comment]
No, I'll not be doing a PR - I have a working solution, and I'm no familiar enough with the code base/documentation to determine what should be included in the PR:

**Comment by MtDalPizzol** [comment]
@mweibel I can't run sync because I have data on my tables, and since sync drops and recreate the tables, I don't want to have to reinsert the data...

**Comment by jakeorr** [comment]
@MtDalPizzol Just a heads up http://docs.sequelizejs.com/en/latest/api/sequelize/?highlight=sync

> options.force=false - If force is true, each DAO will do DROP TABLE IF EXISTS ..., before it tries to create its own table
