### ISSUE TITLE
No Cookies being Set

### ISSUE THREAD

**Issue by Exagram** [mweibel/connect-session-sequelize#34]
I don't see any cookies in my browser pre/post login, express-session generates a new session for all HTTP requests. I expect cookies to appear on my browser and therefore sessions to persist.

Here is my connect-session-sequelize setup:

```javascript
    var SequelizeStore = connectSessionSequelize(session.Store);
    app.use(session({
        secret: 'keyboard-cat-secret',
        genid: function (req) {
            return uuid.v4();
        },
        cookie: {
            httpOnly: true,
            path: '/',
            secure: true
        },
        resave: false,
        saveUninitialized: true,
        store: new SequelizeStore({
            db: dbContext.sequelize
        })
    }));
```

And my login:

```javascript
    app.post('/login', passport.authenticate('local', {
        successReturnToOrRedirect: '/',
        failureRedirect: '/login'
    }));
```

**Comment by mweibel** [comment]
You could try to see what is being logged when starting node with `DEBUG="*"` (e.g. `DEBUG="*" node index.js` and see whether the debug logs from connect-session-sequelize are being logged. As it works for other users of this lib, I assume this must be something in your setup :)

**Comment by Exagram** [comment]
I followed the Express 4 pattern. Curious, is `session.Store` a typo for a `session.MemoryStore`?

`Debug=*` always gives me "express-session: no SID sent, generating session". The rest of my code was aligned with: https://www.npmjs.com/package/passport.

**Comment by mweibel** [comment]
No, it's not a typo. 

Do you have the cookieparser middleware as shown in the usage howto?

**Comment by Exagram** [comment]
I got it! I wrote incorrect Sequelize code which silently failed. Typescript made me code with wrong... types. Oh the irony. Thanks.

**Comment by mweibel** [comment]
:D easy, glad it's resolved :+1:
