### ISSUE TITLE
Race Condition When Used With Passport

### ISSUE THREAD

**Issue by realseanp** [mweibel/connect-session-sequelize#39]
It seems like there is a race condition using the `connect-session-sequelize` in combination with passport for authentication. Passport saves the authenticated user to a session via the `req.login` method. In the callback of `req.login` the user session should be available, but it is not available until the next refresh. When using memory store there is no issue. This leads me to believe that `connect-session-sequelize` is somehow not saving the session in time.

**Comment by jakeorr** [comment]
You are probably seeing this: https://github.com/mweibel/connect-session-sequelize/issues/20

**Comment by realseanp** [comment]
Yep thats what is was. Putting the redirect in the callback of `req.session.save` fixes it.
