### ISSUE TITLE
Getting Bluebird promise warning when router returns no promise

### ISSUE THREAD

**Issue by Typhoon31** [mweibel/connect-session-sequelize#42]
Hi,

I got the following problem:

My 'NODE_ENV' is set to 'development'.
If my route returns no callback, for example:

```js
router.route('/check')
    .get(function (req, res, next) {
        return res.json({});
    });
``` 

I get the following log warning from bluebird:

```
(node:99668) Warning: a promise was created in a handler at C:\xxx\node_modules\express\lib\router\index.js:271:10 but was not returned from it, see http://goo.gl/rRqMUw
    at Function.Promise.attempt.Promise.try (C:\xxx\node_modules\bluebird\js\release\method.js:29:9)
```

If my route returns a promise, this message disappears, for example:

```js
router.route('/check')
    .get(function (req, res, next) {
        q.delay(1000).then(function () {
            return res.json({});
        });
    });
```

The line causing this message is 'connect-session-sequelize.js' at line 108:

```js
return this.sessionModel.update({'expires': expires}, {where: {'sid': sid}}).return(null).asCallback(fn);
```

My question is:
Is this intended? Should I ignore this? I have a bit of code just returning responses (see above) without any promises, so I get this warning in development quite often. (With NODE_ENV different than development, this message disappears)

Many thanks

**Comment by mweibel** [comment]
Thanks for the report, will check what happens there :)

**Comment by mweibel** [comment]
I can't reproduce that. Which bluebird/sequelize/session version do you use?

**Comment by Typhoon31** [comment]
Hi

(some) of my installed packages:
```
connect-session-sequelize    3.1.0
express                      4.14.0	
express-session              1.14.1
sequelize                    3.24.3	
```

The bluebird package comes as sequelize dependency, and is version 3.4.6

```
`-- sequelize@3.24.3
  `-- bluebird@3.4.6
```

It's only happening, when the user is logged in, so I start to believe it's a passport related issue, because I get the following path on login:
```
(node:328444) Warning: a promise was created in a handler at C:\xxx\node_modules\passport\lib\middleware\authenticate.js:201:18 but was not returned from it, see http://goo.gl/rRqMUw
    at Function.Promise.cast (C:\xxx\node_modules\bluebird\js\release\promise.js:195:13)
```
Using latest version of passport and passport-local.

**Comment by Typhoon31** [comment]
I'm going to close this, as I think this is a passport related issue.

I try to investigate this, and maybe file an issue with one of those two packages.

Thanks for your time!

**Comment by Typhoon31** [comment]
Maybe it's still interesting to you:

I found the issue and was able to workaround this. It's an issue with passport-local. The deserializeUser and checkCredentials callback (cb) does not return a promise.

Returning directly resolved or rejected promises (with q) was able so hide this message:
```js
function deserializeUser(id, cb) {

    logger.debug('Deserializing user id: ', id);

    models.User.findById(id)
        .then(function (entry) {

            if (entry) {
                cb(null, entry);
                return q.resolve();
            }
            else {
                cb(null, false);
                return q.resolve();
            }

        })
        .catch(function (err) {
            logger.error('Database error: ', err);
            cb(err);
            return q.reject();
        });
}
```

I'm thinking about it to file an issue with passport-local.

But anyway, thanks for your time!

**Comment by mweibel** [comment]
ok, great :) 
Maybe it would help just retuning the call to `cb`? Not sure about it though ;)

**Comment by Typhoon31** [comment]
Just returning cb did not resolve this. (This was my code, as I reported this)
