### ISSUE TITLE
Really confusing name

### ISSUE THREAD

**Issue by jez9999** [mweibel/connect-session-sequelize#48]
Given that the session architecture for Express is now called `express-session`, this naming is really confusing and I think it should be renamed to `express-session-sequelize`.  It took me a while to figure out that this module actually has nothing to do with the `connect-session` module.

**Comment by jez9999** [comment]
Even if the name of the module isn't changed, its description should be.  Currently it is: "Session store for connect-session using sequelize".  That should be updated to say "express-session".

**Comment by mweibel** [comment]
yeah I agree. Thought the same a while ago but hesitated to rename. Will think about it and figure out the best way to rename.

**Comment by jez9999** [comment]
How long before you rename it?  I want to use it and presumably its npm name will need to change so I'd like it to happen ASAP.

**Comment by mweibel** [comment]
I don't really see a reason to do so and it will pose issues for existing users.
