### ISSUE TITLE
is touch supported so we can use resave false?

### ISSUE THREAD

**Issue by dgobaud** [mweibel/connect-session-sequelize#50]
The Express Session docs https://github.com/expressjs/session recommend setting resave to false but only if the Store supports the touch method. Does this implement touch? The docs should be updated to indicate the answer.

**Comment by mweibel** [comment]
https://github.com/mweibel/connect-session-sequelize/blob/afcad35ff3e89cdde66fde1cba9109ad306360ca/lib/connect-session-sequelize.js#L111

yes ;)
do you have a proposal for how to update the docs?

**Comment by dgobaud** [comment]
thanks! :)
