### ISSUE TITLE
README.md isn't very clear

### ISSUE THREAD

**Issue by Quix0tic** [mweibel/connect-session-sequelize#52]
In your [Usage section](https://github.com/mweibel/connect-session-sequelize#usage) of your README you have the code for `Connect` and the code for `Express 4`.
The problem here is that in the `Connect` code you commented a line that says 

>     // for express, just call it with 'require('express-session').Store'

but in the `Express 4` code you put 

> var SequelizeStore = require('connect-session-sequelize')(session.Store);

Please solve this inconsistency because I was there two days trying to figure out why the recommended code was wrong. Thank you.

**Comment by mattandrews** [comment]
Similarly, the part about syncing the table is a little confusing:

>SequelizeStore.sync() - will run a sequelize sync() operation on the model for an initialized SequelizeStore object. Use this if you would like the the db table to be created for you.

If you use `SequelizeStore.sync()` you'll get an error:

`TypeError: SequelizeStore.sync is not a function`

Really you need to run `sync()` on the instance of `SequelizeStore`, eg:

    var myStore = new SequelizeStore({
        db: sequelize
    }) 
    app.use(session({
        secret: 'keyboard cat',
        store: myStore,
        resave: false, 
        proxy: true
    }))
    
    myStore.sync();

The readme does hint at this but the code in the example will never work.

**Comment by mweibel** [comment]
We welcome any pull requests, also for documentation improvements.

**Comment by mattandrews** [comment]
Good call! Have raised a PR.
