### ISSUE TITLE
Problem with flash messages

### ISSUE THREAD

**Issue by radcapitalist** [mweibel/connect-session-sequelize#53]
Hey,

I posted a question on [StackOverflow](http://stackoverflow.com/questions/42349941/flash-messages-not-working-with-connect-session-sequelize) yesterday about problems I am having with using flash messages with connect-session-sequelize.   I'm curious if you have had other reports of this.  There seems to be a timing problem (though it could certainly be something I'm doing wrong).  

Thanks,

Eric

**Comment by jakeorr** [comment]
You may be running into this: https://github.com/mweibel/connect-session-sequelize/issues/20

**Comment by radcapitalist** [comment]
You are absolutely right!  Saving the session explicitly as described in [#20](https://github.com/mweibel/connect-session-sequelize/issues/53) solves the problem.  I wish I'd have done a better job searching the issues before posting.  Thanks very much!

**Comment by jakeorr** [comment]
Hah, no problem, and you are not the only one. I am becoming an expert at looking up that issue ;)
Glad that solves it for you!
