### ISSUE TITLE
Error :  [Symbol(lt)]: <some_date> 

### ISSUE THREAD

**Issue by miqueloi** [mweibel/connect-session-sequelize#64]
Hi guys

Am I the only one that get this error?

`Unhandled rejection Error: Invalid value { [Symbol(lt)]: 2017-11-19T14:12:26.791Z }`

I had this error in some other part of my program. It happened when I made a query with a 
`{ where: { [Op.lt]: new Date( <later_date> ) } `.
I that case I fixed it by using `Op.gt` instead of `Op.lt`, and it also seems to work for this module.

I read in the docs: [Combinations](http://docs.sequelizejs.com/manual/tutorial/querying.html#combinations) about the difference between gt and lt.

I feel like im missing something basic here?

**Comment by mweibel** [comment]
what does this have to do with this module?

**Comment by miqueloi** [comment]
Ah.. yeah.

in lib/connect-session-sequelize.js:145
`  SequelizeStore.prototype.clearExpiredSessions = function clearExpiredSessions (fn) {
    debug('CLEARING EXPIRED SESSIONS')
    return this.sessionModel.destroy({where: {'expires': {[Op.lt || 'lt']: new Date()}}}).asCallback(fn)
  }`

It is the only place the `lt` operator is used in my entire app. I have thoroughly search all modules and files.  When I tried to change `lt` to `gt` the error went away. But i'm not sure why or if I am misunderstanding something. It looks correct compared to the docs.

**Comment by mweibel** [comment]
Can you try to debug it and/or produce a minimal test case? No idea what happens there. 
Debugging: probably adding console log statements around those lines may help.

**Comment by mweibel** [comment]
Any update? Otherwise I'm closing this issue.
