### ISSUE TITLE
Expose `stopExpiringSessions` so that Mocha 4 can exit gracefully

### ISSUE THREAD

**Issue by glebec** [mweibel/connect-session-sequelize#65]
This bit me hard today. Bear with me while I explain the context.

Mocha 4 has a breaking change. As the [v4 release notes](https://github.com/mochajs/mocha/releases/tag/v4.0.0) indicate:

> By default, Mocha will no longer force the process to exit once all tests complete. This means any test code (or code under test) which would normally prevent node from exiting will do so when run in Mocha. Supply the `--exit` flag to revert to pre-v4.0.0 behavior.

Possible solutions:

- supply `--exit` (easiest, masks true problem)
- downgrade to mocha v3 (easy, masks true problem, regressive)
- use global `after` to cleanup whatever is hanging (best but sometimes hardest)

Following advice from [this Mocha issue](https://github.com/mochajs/mocha/issues/3044) and using a debugging trick from [this gist](https://gist.github.com/boneskull/7fe75b63d613fa940db7ec990a5f5843), I discovered that an undocumented interval was being created by [this line of `connect-session-sequelize`](https://github.com/mweibel/connect-session-sequelize/blob/ab3a3e2c73721a345101a398af2e2073817c9b6f/lib/connect-session-sequelize.js#L152). Thankfully, an undocumented internal implementation method at [this line](https://github.com/mweibel/connect-session-sequelize/blob/ab3a3e2c73721a345101a398af2e2073817c9b6f/lib/connect-session-sequelize.js#L158) meant that the following cleanup hook works:

```js
// in app module

app.set('sessionStore', sessionStore)
```

```js
// in spec

after('clean up resources', () => {
  console.log('stopping session store expiration interval')
  app.get('sessionStore').stopExpiringSessions()
})
```

Now my Mocha tests exit gracefully, because `connect-session-sequelize` isn't keeping the process alive indefinitely. Arguably, `connect-session-sequelize` ought to have a public API method to tell it to stop persisting the process so that it can be properly cleaned up in similar cases.

**Comment by mweibel** [comment]
That sounds reasonable. However: I had the same issue recently with the tests in this very module:
https://github.com/mweibel/connect-session-sequelize/commit/cbaa4b03a66c38e8237c81d08e2276e346aa85c7

How about you'd also just give an expiration interval of -1 when in the tests?

**Comment by glebec** [comment]
@mweibel, you could definitely do so, but then you are modifying the session store behavior for testing, rather than cleaning up resources after testing. On principle I prefer to keep testing environment as close to production as is reasonable.

**Comment by mweibel** [comment]
True. Though my question is what would you like to change? stopExpiringSession is already a public API. I'd welcome a PR.

**Comment by glebec** [comment]
It’s publicly exposed but not documented, making it arguably an implementation detail rather than an API method. Explicitly documenting it as a feature would both aid in discovery and also signal that it is ok to use and will be tracked in SEMVER.

**Comment by mweibel** [comment]
Ok, I see. Please open a PR with your proposed change and I'll gladly review it.
