### ISSUE TITLE
Writing to database on every request

### ISSUE THREAD

**Issue by crisward** [mweibel/connect-session-sequelize#67]
This seems to write to the database on every request. 

Could it have a threshold added, so it only updates the database every minute, or a user configurable period, based on the updated_at time?

**Comment by mweibel** [comment]
You're welcome to open a PR with the proposed change.
What's the reason for this request?

**Comment by crisward** [comment]
I've been trying to optimise an application, the biggest bottleneck tends to be the database, so I've been looking to reduce the number of queries and updates. Selecting and updating the session time on every request seems excessive. On high traffic sites we use Redis, but it'd nice to be able to avoid the extra dependency if we can squeeze a bit more our of this module.

I'll see what I can do about a PR.

**Comment by tony-gutierrez** [comment]
I came here looking for this option as well. I don't need millisecond level expiration updates. It tends to do a lot of db writing.

**Comment by mweibel** [comment]
I welcome any PR 👍

**Comment by tony-gutierrez** [comment]
It looks like there are some problems with trying to solve this in this library. 

You would basically have to do a read in order to know not to do an update, so that isnt going to really help.

This might be something that is better solved at the "connect" library level.

**Comment by tony-gutierrez** [comment]
I'm actually not sure why touch() is being called by "express-session" on every request? I cant seem to disable rolling updates in the "express-session" library.

**Comment by tony-gutierrez** [comment]
See here: https://github.com/expressjs/session/pull/531

**Comment by tony-gutierrez** [comment]
I think the best thing that could be done in this library is to offer an option that would basically disable the touch() method from doing anything. That way the user can force a save() on the session by updating its variables, and not worry about the db being written to every request.

**Comment by tony-gutierrez** [comment]
Added PR #70

**Comment by mweibel** [comment]
fixed in #70 
Release coming soon

**Comment by mweibel** [comment]
released version 5.2.0 on npm.
