### ISSUE TITLE
sequelize 4.28.5 deprecated String based operators are now deprecated. 

### ISSUE THREAD

**Issue by onlyling** [mweibel/connect-session-sequelize#68]
```json
{
    "dependencies": {
        "sequelize": "^4.28.5",
        "connect-session-sequelize": "^5.1.0",
        "express-session": "^1.15.6",
    }
}
```
> sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules/sequelize/lib/sequelize.js:236:13

and

```javascript
var app = express()
app.use(cookieParser())
app.use(session({
    saveUninitialized: true, // need
    secret: 'keyboard cat',
    store: new SequelizeStore({
        db: sequelize
    }),
    resave: false,
    proxy: true
}))
```
> express-session deprecated undefined saveUninitialized option; provide saveUninitialized option app/app.js:49:9

**Comment by mweibel** [comment]
#59 fixed the string based operators. 
About `saveUnitialized` that's "just" docs, right? I'd welcome a PR for that, thanks!

**Comment by onlyling** [comment]
`saveUnitialized` was the console that reported the error(info?).
