### ISSUE TITLE
Set session race condition

### ISSUE THREAD

**Issue by jakeorr** [mweibel/connect-session-sequelize#7]
I haven't been able to track down what's causing this problem, but something changed with [express-session](https://github.com/expressjs/session) starting at version 1.6. I'm seeing the behaviour on a web app I'm building when there are changed in the authentication status (login/logout). The site will perform a login (using passport) and then redirect to the main page. The behaviour I'm seeing is that the store's `.set()` method is being called, but before it completes, the `.get()` method is called for authentication on new page, returning the old, non-authenticated session. This results in a redirect back to the login page which now sees the new authenticated session and redirects again to the app page. This continues until fail with too many redirects.

I found this issue which sounds like it refers to a similar problem, but I haven't been able to figure out how it applies: https://github.com/expressjs/session/issues/52

**Comment by chriswininger** [comment]
@jakeorr The issue I run into when I make resave false and/or generally limit my session changes to a few necessary requests, is that then the session expires date never gets updated in mongo. This leads to the session expiring out from under a user who is actively using the page. Once I start touching the session and making sure it saves for more the requests then I get back into this race condition where a user tries to logout but before being redirected to login another request finishes and re-saves the session in an authenticated state. I'm winding up with lots of manual calls to save the save the session at the end of requests wrapped in locking mechanisms. This doesn't seem good.

**Comment by jakeorr** [comment]
Hi @chriswininger, I don't think I've run into the issue with expiry dates that you're describing. Do you require short expiration periods? Is increasing the expiration time an option for you? I agree that the manual calls to save in endpoints isn't ideal, but I don't have a better solution at this point. For what it's worth, I didn't end up needing to use the `save(cb)` solution in many spots. It may have just been a different type of situation than you're seeing, but perhaps there is a better way for you to set things up.
