### ISSUE TITLE
Sequelize deprecated warning

### ISSUE THREAD

**Issue by wilzoka** [mweibel/connect-session-sequelize#79]
Sequelize latest version throw a deprecated warning:

"sequelize deprecated Model.find has been deprecated, please use Model.findOne instead node_modules\sequelize\lib\model.js:4212:9"

**Comment by rdhelms** [comment]
Examples:
https://github.com/mweibel/connect-session-sequelize/blob/master/lib/connect-session-sequelize.js#L63
```
    return this.sessionModel.find({where: {'sid': sid}}).then(function (session) {
```

https://github.com/mweibel/connect-session-sequelize/blob/master/lib/connect-session-sequelize.js#L138
```
    return this.sessionModel.find({where: {'sid': sid}, raw: false}).then(function foundSession (session) {
```

**Comment by mweibel** [comment]
Feel free to open a PR.
