### ISSUE TITLE
successRedirect passport and sequelize store

### ISSUE THREAD

**Issue by nrics** [mweibel/connect-session-sequelize#82]
I have to do req.session.save and cant use successRedirect with Pasport and SequelizeStore.

router.post('/login', passport.authenticate('local', {
    failureRedirect: '/login'
}), (req, res) => {
    // req.session.userId = user.id;

    // Add this :
    req.session.save(function() {             
        return res.redirect('/registered');
    });

});

is this fixed already? thank you

**Comment by mweibel** [comment]
To know whether something is a bug or is fixed or whatever else, we need to know a bit more.
Please include a proper bug report with what you encounter, what you want to achieve, what doesn't work, logs, example code (more than just this snippet), etc.
