### ISSUE TITLE
touch and set to update table field `expires` from cookie

### ISSUE THREAD

**Issue by adminparry** [mweibel/connect-session-sequelize#89]
var expires 
if (data.cookie && data.cookie.expires) {
 expires = data.cookie.expires
 } else {
      expires = new Date(Date.now() + this.options.expiration)
}

don`t use the cookie.expires example:
the client set cookie max age is 1day
the server set session 15minute and touch add minute to keep login status

so if user wanna cookie and session together can set cookie.expires = expiration

**Comment by mweibel** [comment]
What is this issue about?
