### ISSUE TITLE
Executes 30+ queries on page load

### ISSUE THREAD

**Issue by olingern** [mweibel/connect-session-sequelize#91]
Not sure why this is happening. But page loads went from ~10ms to 3+ seconds. 

I have logging turned on for sequelize. Here's a screenshot of my output:

![image](https://user-images.githubusercontent.com/1470297/61071778-dfc1ca80-a44c-11e9-8085-c50bd9b76ca8.png)

**Comment by mweibel** [comment]
I've no idea as well - reproduction steps would be nice in such cases. Until then -> close.
