### ISSUE TITLE
Expiration equivalent to cookie.expires = false

### ISSUE THREAD

**Issue by bobopland** [mweibel/connect-session-sequelize#94]
As far as I understand, the session expiry is first fetched from the cookie (cookie.expires) and if no value is set, it gets fetched from the store setting (expiration).

If my value for cookie.expires is "false", which means that the session expires whenever the user closes the browser/tab, is then the value retrieved from the store (expiration)? Is there a way to tell the store to delete the record whenever the cookie is deleted? Or does the session stay in the database as long as expiration defines when cookie.expires is false? 

Thanks for your help man, really appreciate it!

**Comment by mweibel** [comment]
that's probably more of a question towards express. Just try it out ;)

>  there a way to tell the store to delete the record whenever the cookie is deleted

As the server side doesn't know when the browser deletes a cookie, the answer to this is: no.
